[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# These redirects are needed for Next.js routes to work correctly
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 